using System;
using System.Windows;

namespace NGU.Lab13.Views
{
    /// <summary>
    /// Interaction logic for AiReportWindow.xaml.
    /// Displays the detailed text report generated by the Gemini API in a scrollable, copyable format.
    /// </summary>
    public partial class AiReportWindow : Window
    {
        /// <summary>
        /// Default constructor (mostly for WPF designer support).
        /// </summary>
        public AiReportWindow()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Constructor that accepts the report content text.
        /// </summary>
        /// <param name="reportText">The markdown or plain text report returned from Gemini.</param>
        public AiReportWindow(string reportText)
        {
            InitializeComponent();
            
            // Set the TextBox content to our report text
            txtReportContent.Text = reportText;
        }

        /// <summary>
        /// Copies the text inside the report TextBox directly to the Windows Clipboard.
        /// </summary>
        private void OnCopyToClipboardClick(object sender, RoutedEventArgs e)
        {
            try
            {
                if (!string.IsNullOrEmpty(txtReportContent.Text))
                {
                    Clipboard.SetText(txtReportContent.Text);
                    MessageBox.Show("AI Report copied to clipboard successfully!", "Copied", MessageBoxButton.OK, MessageBoxImage.Information);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to copy text: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// Closes the report dialog.
        /// </summary>
        private void OnCloseClick(object sender, RoutedEventArgs e)
        {
            this.Close();
        }
    }
}
